 import React from 'react'
 
 function AboutPage() {
   return (
     <div>About Page</div>
   )
 }

 export const metadata = {
   title: 'About Page',
   description: 'Generated by create next app',
 }
 
 export default AboutPage